env:
  global:
    - CC_TEST_REPORTER_ID=b84d24d87a44d1bc041abe37a4e8c4bae44e5691b136ec6a37df73b3bf6b8ca4
language: node_js
node_js:
  - "lts/*"
services:
  - docker
before_install:
  - docker pull rabbitmq:latest
  - docker pull redis:latest
  - docker build ./containers/celery -t celery
  - docker network create celery
  - docker run rabbitmq --name rabbitmq --network celery -p 5672:5672 -d
  - docker run redis --name redis --network celery -p 6379:6379 -d
  - docker run celery --name celery --network celery -d
before_script:
  - npm run setup
  - npm run build
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
  - ./cc-test-reporter format-coverage --output "coverage/codeclimate.1.json"
  - npm test-integration
  - ./cc-test-reporter format-coverage --output "coverage/codeclimate.0.json"
after_script:
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json
  - ./cc-test-reporter upload-coverage
before_deploy:
  - npm pack
  - npm run typedoc
deploy:
  - provider: npm
    skip-cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_API_KEY
    on:
      branch: master
      tags: true
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: develop
    local-dir: docs
